### ISSUE TITLE
Blurry texts in cards in canvas

### ISSUE THREAD

**Issue by trangodjango** [erykwalder/dayspring-theme#1]
In new core plugin, Canvas, when zooming in the canvas for like 75%, the text is so blurry, only the text in note cards is visible. Besides that, the theme works great, it is one of my favorite themes I use to romanticize my writing

**Comment by erykwalder** [comment]
Hi, I may ask if you can add screenshots. I haven't used canvas much myself, so I may be missing it. I tried what you were saying, and although I saw a little blur, it wasn't more than I'd expect with resizing down. I didn't see a difference between cards and notes in the canvas. I think the way canvas works it doesn't resize the font down, but just scales the rendering (just my guess, not sure).

Also, do you have the fonts locally installed? Figtree? And Crimson Pro if you're using the alt style?

**Comment by trangodjango** [comment]
![Blurry Canvas zoom in](https://user-images.githubusercontent.com/89115637/212465274-380b47d5-a665-4f77-be5a-c5da72d0eaa5.png)
Hi, here is the screenshot of my Canvas. I didn't have the fonts locally installed, so it could be the reason (because when I used Canvas with other themes, the card text visibility is totally ok without the custom fonts, so I thought it applies to every theme on Obsidian) and it was probably because I have a small inch laptop screen, so it was a bit difficult for me to see the card texts. In overall, it's not a really major bug.

**Comment by erykwalder** [comment]
If you get a chance, try the latest update and let me know if it helps

**Comment by trangodjango** [comment]
The texts in the cards are still blurry for me, but it doesn't matter much, thank you for updating the theme
